
# project name, lowercase and underscores only
# does not need to match the dbt directory name but convention keeps them the same
# this name is used internally by dbt and must match the name under models: in this file
# version is just a label, update manually to track releases
name: 'projecta'
version: '1.0.0'

# profile tells dbt which connection profile to use from ~/.dbt/profiles.yml
# projecta is the profile name that holds the Supabase database credentials
profile: 'projecta'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


# clean-targets lists folders deleted when running dbt clean
# target/ holds compiled SQL, run logs and artifacts generated by dbt
# dbt_packages/ holds installed dbt packages
# dbt clean is used to reset and clear cached artifacts so dbt starts fresh on the next run
clean-targets: 
  - "target"
  - "dbt_packages"


# models/dbt_projecta/ maps each subfolder to its corresponding database schema
# silver/ folder maps to silver schema, gold/ folder maps to gold schema
# + prefix means the config applies to all .sql files inside that folder
# when ref() is used in a model, dbt finds the referenced .sql file, checks its folder location here
# and maps it to the correct database schema so it knows where to create or materialize the table

models:
  projecta:
    silver: # silver: is the folder in models/, +schema: silver tells dbt that all .sql files inside that folder belong to the silver database schema.
      +schema: silver
    gold: # gold: is the folder in models/, +schema: gold tells dbt that all .sql files inside that folder belong to the gold database schema.
      +schema: gold 


