# name of the workflow, shows up in Github Actions tab
name: ProjectA dbt Scheduler

# when to trigger the workflow
on:
  schedule:
    # cron format: minute hour day month weekday
    # runs 1 hour after each ProjectA Data Generator workflow
    - cron: '0 7 * * *'
    - cron: '0 13 * * *'
    - cron: '0 19 * * *'
    - cron: '40 0 * * *'
  # workflow_dispatch adds a manual trigger button in the GitHub Actions tab
  # useful for testing without waiting for the cron schedule to fire
  workflow_dispatch:

# defines the jobs to run
jobs:
  dbt_scheduler: # job name, just an identifier
    runs-on: ubuntu-24.04 # spins up a fresh Ubuntu virtual machine hosted by GitHub. Pinned to 24.04 because ubuntu-latest moves to Ubuntu 26 on Oct 19, 2026 and could break the dbt install
    # injects DATABASE_URL secret as environment variable, available before any steps run
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4 # GitHub action at version 4 that clones the entire repository onto the VM

      - name: Set up Python # installs Python 3.10, required since dbt-postgres is a Python package
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # mkdir -p creates the .dbt directory on the VM if it does not exist
      # cat '>' creates the profiles.yml file and writes content to it, '>' overwrites if it already exists
      # '<<' EOF (heredoc) keeps the file open for writing until the closing EOF is reached
      # VMs are fresh on every run so the profiles file does not exist until this step creates it
      # credentials are pulled from GitHub secrets, nothing sensitive is stored in the codebase
      - name: Create dbt profiles
        run: |
          mkdir -p /home/runner/.dbt
          cat > /home/runner/.dbt/profiles.yml << 'EOF'
          projecta:
            outputs:
              dev:
                type: postgres
                host: ${{ secrets.DB_HOST }}
                user: ${{ secrets.DB_USER }}
                password: ${{ secrets.DB_PASSWORD }}
                port: 5432
                dbname: postgres
                schema: public
                threads: 1
            target: dev
          EOF

      - name: Install dbt # installs dbt-postgres, --no-build-isolation bypasses SSL GitHub download error
        run: pip install dbt-postgres==1.8.2  dbt-core==1.8.7 --no-build-isolation

      - name: Install dbt dependencies # installs packages listed in packages.yml such as dbt_utils
        run: dbt deps
        working-directory: dbt_projecta

      - name: Run dbt transformation # runs all dbt models in dependency order, silver first then gold
        run: dbt run
        working-directory: dbt_projecta

      - name: Run dbt quality tests # runs all data quality tests defined in schema.yml
        run: dbt test
        working-directory: dbt_projecta
